"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { useRouter } from "next/navigation";
import { FreeTextInput } from "./free-text-input";
import { GuidedWizard } from "./guided-wizard";

type InputMode = "free_text" | "guided";

interface Sector {
  id: string;
  name: string;
  parent_id: string | null;
}

interface Theme {
  id: string;
  name: string;
  icon: string | null;
}

interface NewPlaybookClientProps {
  userId: string;
  sectors: Sector[];
  subsectors: Sector[];
  themes: Theme[];
}

export function NewPlaybookClient({
  userId,
  sectors,
  subsectors,
  themes,
}: NewPlaybookClientProps) {
  const [mode, setMode] = useState<InputMode>("free_text");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();
  const supabase = createClient();

  const handleFreeTextSubmit = async (title: string, rawInput: string) => {
    setSubmitting(true);
    setError(null);

    // Create thesis row with raw_input, status = draft
    const { data: thesis, error: insertError } = await supabase
      .from("usr_theses")
      .insert({
        user_id: userId,
        title: title.trim(),
        raw_input: rawInput.trim(),
        input_mode: "free_text",
        status: "draft",
      })
      .select("id")
      .single();

    if (insertError || !thesis) {
      setError("Failed to create playbook. Please try again.");
      setSubmitting(false);
      return;
    }

    // TODO: Call parse-thesis edge function once deployed
    // For now, redirect to the playbook detail page
    router.push(`/playbooks/${thesis.id}`);
  };

  const handleGuidedSubmit = async (data: {
    title: string;
    sectors: string[];
    themes: string[];
    growth_preference: string;
    size_preference: string[];
    geographic_focus: string;
    profitability: string;
    conviction: string;
  }) => {
    setSubmitting(true);
    setError(null);

    // Build structured_criteria directly (skip parse-thesis)
    const structuredCriteria = {
      sectors: data.sectors,
      themes: data.themes,
      company_characteristics: {
        growth_preference: data.growth_preference,
        size_preference: data.size_preference,
        geographic_focus: data.geographic_focus,
        profitability: data.profitability,
      },
      thesis_summary: data.conviction,
      search_queries: [], // Will be generated by source-companies
    };

    // Create thesis row with structured_criteria, status = active (skips parse)
    const { data: thesis, error: insertError } = await supabase
      .from("usr_theses")
      .insert({
        user_id: userId,
        title: data.title.trim(),
        raw_input: data.conviction.trim(),
        input_mode: "guided",
        status: "active",
        structured_criteria: structuredCriteria,
      })
      .select("id")
      .single();

    if (insertError || !thesis) {
      setError("Failed to create playbook. Please try again.");
      setSubmitting(false);
      return;
    }

    // Store guided responses for reference
    await supabase.from("usr_thesis_responses").insert({
      thesis_id: thesis.id,
      responses: data,
    });

    // TODO: Call source-companies edge function once deployed
    router.push(`/playbooks/${thesis.id}`);
  };

  return (
    <div>
      {/* Mode toggle */}
      <div className="flex gap-1 p-1 bg-neutral-100 rounded-lg mb-6 w-fit">
        <button
          onClick={() => setMode("free_text")}
          className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
            mode === "free_text"
              ? "bg-white text-neutral-900 shadow-sm"
              : "text-neutral-500 hover:text-neutral-700"
          }`}
        >
          Free-text
        </button>
        <button
          onClick={() => setMode("guided")}
          className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
            mode === "guided"
              ? "bg-white text-neutral-900 shadow-sm"
              : "text-neutral-500 hover:text-neutral-700"
          }`}
        >
          Guided
        </button>
      </div>

      {/* Input mode content */}
      {mode === "free_text" ? (
        <FreeTextInput onSubmit={handleFreeTextSubmit} submitting={submitting} />
      ) : (
        <GuidedWizard
          sectors={sectors}
          subsectors={subsectors}
          themes={themes}
          onSubmit={handleGuidedSubmit}
          submitting={submitting}
        />
      )}

      {error && <p className="text-sm text-red-600 mt-4">{error}</p>}
    </div>
  );
}
